name: fire_auth_quick
description: "A Flutter plugin for social login and account linking with Google, Facebook, and Apple."
version: 2.2.2
homepage: https://github.com/minhto2811/fire_auth_quick
topics:
  - login
  - auth
  - firebase

environment:
  sdk: ^3.5.1
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^6.7.0
  google_sign_in: ^7.2.0
  google_sign_in_all_platforms_desktop: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
